formatter: "markdown"

sort:
  enabled: true
  by: required

content: |-
  # aws ecs fargate terraform module
  
  ### Usage

  [For examples and refrences click here.](https://github.com/Rishang/terraform-aws-fargate/tree/main/examples)

  {{ include "examples/example.md" }}

  
  {{ .Providers }}

  {{ .Outputs }}

  ## available tfvar inputs

  ```hcl
  # null are required inputs, 
  # others are optional default values

  {{ include "vars/example.tfvars" }}
  ```

  {{ .Inputs }}

  ---
  README.md created by: `terraform-docs`

output:
  file: "./README.md"
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
