formatter: "markdown"

content: |-
  # terraform module for aws ecs fargate
  
  ### Example

  {{ include "examples/example.md" }}

  {{ .Providers }}

  {{ .Outputs }}

  {{ .Inputs }}

  ## tfvar inputs

  ```hcl
  {{ include "vars/example.tfvars" }}
  ```

  ---
  README.md created by: `terraform-docs`

output:
  file: "./README.md"
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
